### ISSUE TITLE
[PE-D][Tester D] Bug: Edit student with multiple telegram handles

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-4/tp#161]
Here I ran the command `edit 1 t/hello t/how t/are t/you t/doing`.
You can see that the telegram handle is @doing. This can confuse users who want to edit tags instead of telegram handle and mistake tag for t.
You can consider only allowing one t/ parser per edit command instead. 

![image.png](https://raw.githubusercontent.com/bryanngzh/ped/main/files/295dd16c-efeb-4fc7-88fa-b277ca7d513f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: bryanngzh/ped#8

**Comment by HowSuen** [comment]
Telegram handles are specified with "t/" whereas tags are specified with "tag/".
Furthermore, if a parameter is specified more than once, only the latest occurrence of the parameter will be taken.

![image](https://user-images.githubusercontent.com/82646869/198815013-c421f09a-86af-4403-877b-24f46341195d.png)
